package com.cjh.community2.model;

public class Notification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.id
     *
     * @mbg.generated Wed Jul 15 18:02:16 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.notifier
     *
     * @mbg.generated Wed Jul 15 18:02:16 CST 2020
     */
    private Long notifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.receiver
     *
     * @mbg.generated Wed Jul 15 18:02:16 CST 2020
     */
    private Long receiver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.outerid
     *
     * @mbg.generated Wed Jul 15 18:02:16 CST 2020
     */
    private Long outerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.type
     *
     * @mbg.generated Wed Jul 15 18:02:16 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.gmtcreate
     *
     * @mbg.generated Wed Jul 15 18:02:16 CST 2020
     */
    private Long gmtcreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.status
     *
     * @mbg.generated Wed Jul 15 18:02:16 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.NOTIFIER_NAME
     *
     * @mbg.generated Wed Jul 15 18:02:16 CST 2020
     */
    private String NOTIFIER_NAME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.OUTER_TITLE
     *
     * @mbg.generated Wed Jul 15 18:02:16 CST 2020
     */
    private String OUTER_TITLE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.id
     *
     * @return the value of notification.id
     *
     * @mbg.generated Wed Jul 15 18:02:16 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.id
     *
     * @param id the value for notification.id
     *
     * @mbg.generated Wed Jul 15 18:02:16 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.notifier
     *
     * @return the value of notification.notifier
     *
     * @mbg.generated Wed Jul 15 18:02:16 CST 2020
     */
    public Long getNotifier() {
        return notifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.notifier
     *
     * @param notifier the value for notification.notifier
     *
     * @mbg.generated Wed Jul 15 18:02:16 CST 2020
     */
    public void setNotifier(Long notifier) {
        this.notifier = notifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.receiver
     *
     * @return the value of notification.receiver
     *
     * @mbg.generated Wed Jul 15 18:02:16 CST 2020
     */
    public Long getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.receiver
     *
     * @param receiver the value for notification.receiver
     *
     * @mbg.generated Wed Jul 15 18:02:16 CST 2020
     */
    public void setReceiver(Long receiver) {
        this.receiver = receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.outerid
     *
     * @return the value of notification.outerid
     *
     * @mbg.generated Wed Jul 15 18:02:16 CST 2020
     */
    public Long getOuterid() {
        return outerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.outerid
     *
     * @param outerid the value for notification.outerid
     *
     * @mbg.generated Wed Jul 15 18:02:16 CST 2020
     */
    public void setOuterid(Long outerid) {
        this.outerid = outerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.type
     *
     * @return the value of notification.type
     *
     * @mbg.generated Wed Jul 15 18:02:16 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.type
     *
     * @param type the value for notification.type
     *
     * @mbg.generated Wed Jul 15 18:02:16 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.gmtcreate
     *
     * @return the value of notification.gmtcreate
     *
     * @mbg.generated Wed Jul 15 18:02:16 CST 2020
     */
    public Long getGmtcreate() {
        return gmtcreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.gmtcreate
     *
     * @param gmtcreate the value for notification.gmtcreate
     *
     * @mbg.generated Wed Jul 15 18:02:16 CST 2020
     */
    public void setGmtcreate(Long gmtcreate) {
        this.gmtcreate = gmtcreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.status
     *
     * @return the value of notification.status
     *
     * @mbg.generated Wed Jul 15 18:02:16 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.status
     *
     * @param status the value for notification.status
     *
     * @mbg.generated Wed Jul 15 18:02:16 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.NOTIFIER_NAME
     *
     * @return the value of notification.NOTIFIER_NAME
     *
     * @mbg.generated Wed Jul 15 18:02:16 CST 2020
     */
    public String getNOTIFIER_NAME() {
        return NOTIFIER_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.NOTIFIER_NAME
     *
     * @param NOTIFIER_NAME the value for notification.NOTIFIER_NAME
     *
     * @mbg.generated Wed Jul 15 18:02:16 CST 2020
     */
    public void setNOTIFIER_NAME(String NOTIFIER_NAME) {
        this.NOTIFIER_NAME = NOTIFIER_NAME == null ? null : NOTIFIER_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.OUTER_TITLE
     *
     * @return the value of notification.OUTER_TITLE
     *
     * @mbg.generated Wed Jul 15 18:02:16 CST 2020
     */
    public String getOUTER_TITLE() {
        return OUTER_TITLE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.OUTER_TITLE
     *
     * @param OUTER_TITLE the value for notification.OUTER_TITLE
     *
     * @mbg.generated Wed Jul 15 18:02:16 CST 2020
     */
    public void setOUTER_TITLE(String OUTER_TITLE) {
        this.OUTER_TITLE = OUTER_TITLE == null ? null : OUTER_TITLE.trim();
    }
}